# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Legend.create!(name: "Valkyrie", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/valkyrie-tile.png", passive_name: "VTOL JETS", passive_image_url: "https://i.imgur.com/FMnmfyT.png", tactical_name: "MISSLE SWARM", tactical_image_url: "https://i.imgur.com/mwU1Lky.png", ultimate_name: "SKYWARD DIVE", ultimate_image_url: "https://i.imgur.com/cnP9X0S.png", lore: "Bold, brash, fiery and fierce, Kairi Imahara isn’t above greasing palms and bending the law. When she was a child, she stole a Titan. It belonged to her dad: callsign Viper. She wanted to be just like him when she grew up. But the next day he left on a mission and never returned. In some ways, she still followed in his footsteps: it wasn't a Titan, but her ship offered a decent living. Her personal life, however, was anything but. During the day, she smuggled precious cargo, and at night, went shot for shot with the outlaws and mercs in the bars. But even though she had her ladies, her liquor, and her love of the sky, she was still obsessed with finding the man who’d put her father in harm’s way: his commander, Kuben Blisk. She tracked Blisk down, prepared to kill him. But he spoke of her father with respect -- and challenged her to be better. She shot him anyway. But not to kill. Knowing she could get to him was enough. Well, that, and the Apex Games card she took from Blisk’s grasp. Using the intact flight core from Viper’s Northstar, she built a sleek new jetpack that honored her father’s memory. And that was when Kairi could finally soar on her own… and in a version of her dad’s Titan, a modified Northstar with an enhanced VTOL and flight core, that ended up being hers after all.")
Legend.create!(name: "Fuse", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/fuse-tile.png", passive_name: "GRENADIER", passive_image_url: "https://i.imgur.com/WKzjo0q.png", tactical_name: "KNUCKLE CLUSTER", tactical_image_url: "https://i.imgur.com/UdPJGKl.png", ultimate_name: "THE MOTHERLODE", ultimate_image_url: "https://i.imgur.com/LTMF08Y.png", lore: "Ladies’ man, man’s man, and all-round manly man, Fuse is a one-man wrecking crew... and he knows it. Fuse exudes joy; he’s a laid-back explosives enthusiast who’s damn near covered in things that go BOOM. Fuse doesn’t lack confidence, but he often lacks a plan. He’s a blow-up-first ask-questions-later kinda guy, who’s always looking for a good scrap. Fuse grew up on Salvo--a brutal planet ruled by a rotating collection of misfit warlords bent on mayhem, murder, and good times. For most of his life, he worked as a mercenary alongside his childhood friend, Maggie. But while she aspired to become one of Salvo’s most powerful warlords, Fuse felt the pull of the arena. Fuse found his calling late in life-fighting in Salvo’s bloodsport: the Bonecage. He proved to be the best, most charismatic, and beloved gladiator on the planet. But he itched to join the grandest stage of them all: the Apex Games. While Salvo remained a part of Independent Space that dream was impossible, but once they joined the Syndicate, his chance arrived. It came at a price, however -- Maggie wouldn’t let him go without a fight.")
Legend.create!(name: "Horizon", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/horizon-tile.png", passive_name: "SPACEWALK", passive_image_url: "https://i.imgur.com/mebgNH3.png", tactical_name: "GRAVITY LIFT", tactical_image_url: "https://i.imgur.com/RShBdYD.png", ultimate_name: "BLACK HOLE", ultimate_image_url: "https://i.imgur.com/3bfKBPM.png", lore: "Almost a century ago, the Outlands were dangling on the edge of a cataclysmic energy crisis. Dr. Mary Somers, a charmingly eccentric astrophysicist, was hired to find a solution. Mary moved her family to the scientific research station on Olympus and set to work. With the help of her apprentice, Dr. Reid, Mary discovered Branthium - an element she was convinced could be the key to limitless energy. But Branthium can be found only on the accretion disk of a black hole, so Mary and Dr. Reid departed on a dangerous mission to prove her theory right. Mary promised her son Newton she’d return safe and sound. But Dr. Reid betrayed her, stealing the Branthium and sending her shuttle into the black hole’s orbit. Using her wits, Mary modified her robotic vacuum companion N.E.W.T. to escape. But time moves differently on the outskirts of a black hole, and she was 87 years too late. Now Mary is determined to fund her research to find a way to go back in time and be with her son. She joins the Apex Games as Horizon, master of gravity, just in time for the next season to debut on Olympus - where her old life once was and where she had promised to return.")
Legend.create!(name: "Rampart", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/rampart-tile.png", passive_name: "MODDED LOADER", passive_image_url: "https://i.imgur.com/ldwgxqe.png", tactical_name: "AMPED COVER", tactical_image_url: "https://i.imgur.com/1Zeqc9Y.png", ultimate_name: "EMPLACED MINIGUN - SHIELA", ultimate_image_url: "https://i.imgur.com/aLkgXIM.png", lore: "Rampart is a blue-collar, private business owner who just needs a big gun and a backpack full of scrap metal to get by in the dangerous, wild west world of the Outlands. Before opening her popular modding shop on Gaea, Ramya Parekh made a name for herself in the underground gauntlet circuit. Parekh climbed to the top showcasing pure skill using her custom-modded gear. She began taking jobs from smugglers, Syndicate members, and everyone in between. Some say it ain't great unless it's got Rampart written on it. Parekh never shied away from letting people know how great she was, or better yet, how bad they were. Maybe that's what led a group of assailants to ambush her at her shop one night. Her business burned down and she was left with nothing -- except an Apex Card. For Parekh, the Apex card is more than just an invitation to compete - it's a sign that she may have lost her shop, but she didn't lose what built it. Like her motto says, she's the kind of person who can always turn crap into gold.")
Legend.create!(name: "Loba", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/loba-tile.png", passive_name: "EYE FOR QUALITY", passive_image_url: "https://i.imgur.com/akhdcdh.png", tactical_name: "BURGLAR'S BEST FRIEND", tactical_image_url: "https://i.imgur.com/QlWB0Pk.png", ultimate_name: "BLACK MARKET BOUTIQUE", ultimate_image_url: "https://i.imgur.com/wNqZmO3.png", lore: "When Loba was nine, she looked on as simulacrum hitman Revenant killed her parents. Left with nothing, Loba was given to a foster family. But like her mother and father, she quickly found out she was good at being a thief. She started with picking pockets and as her skills improved, Loba used every tool at her disposal to lift herself from the gutter. Everything changed when she broke into a supposedly impenetrable facility and got her hands on the Jump Drive tech stored inside. With her new teleportation bracelet, the most secure and unattainable items were within her reach. So was her dream of living the high life. Rumors spread across the Outlands: if you wanted something valuable -and well guarded- Loba's who you go to. She was almost able to put her past behind her. But when Revenant joined the Games, her past catapulted into her future. Desperate to find a way to kill him, she found out the truth about the Simulacrum with help from her friend Jaime and successfully sabotaged a facility full of Revenant bodies, bringing Skull Town and Thunderdome crashing down in the process. However, she learned it was just one of many such factories hidden across the Frontier. Now, she's joined the Games to find a way to end him for good. It doesn't hurt that the Arenas are brimming with treasures just waiting to be plucked. Revenge will come, if fortune favors her. In the meantime, some shiny things have caught her eye.")
Legend.create!(name: "Revenant", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/revenant-tile.png", passive_name: "STALKER", passive_image_url: "https://i.imgur.com/ZBXq2M9.png", tactical_name: "SILENCE", tactical_image_url: "https://i.imgur.com/ZXg4ODd.png", ultimate_name: "DEATH TOTEM", ultimate_image_url: "https://i.imgur.com/RxI57yL.png", lore: "Revenant used to be human. He used to be the greatest hitman the Mercenary Syndicate ever had. He used to look in the mirror and see his human face looking back. Then one day, he finally saw what he had become at the hands of the Mercenary Syndicate and Hammond Robotics: a walking nightmare of steel and vestigial flesh. The simulacrum Revenant first booted up in 2420, though it took another twenty years for the robotic shell to function properly, after which he was delivered to the Syndicate for their use. For three centuries Revenant has been an agent of death for the Syndicate, type the name of the target, and a day later they're dead. When Revenant himself dies, his masters resurrected him again and again, snatching him from death’s embrace and programming him to forget.But one day, after killing Marcos and Alanza Andrade, he looked at a mirror and finally saw himself for what he had become. He swore that he would hunt down every last person who did this to him, but more than two centuries have passed, and they're all gone… or so he thought. The return of Hammond Robotics to the Outlands has renewed his thirst for vengeance, he snuck into their facilities, trying to find out more about himself. When an interview with Forge, a Legend sponsored by Hammond, was conducted in World's Edge he went there and killed him. He wasn't the first nor would he be the last, for he won’t stop until anybody connected to Hammond is dead. Of course, he doesn’t mind eviscerating a few of the Legends along the way. He used to need a reason to kill… but he’s not that man anymore.")
Legend.create!(name: "Crypto", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/crypto-tile.png", passive_name: "NEUROLINK", passive_image_url: "https://i.imgur.com/kwgCCSX.png", tactical_name: "SURVEILLANCE DRONE", tactical_image_url: "https://i.imgur.com/LCY7MT3.png", ultimate_name: "DRONE EMP", ultimate_image_url: "https://i.imgur.com/DW8HZws.png", lore: "Crypto specializes in secrets; he knows how to uncover them, and how to keep them. A brilliant hacker and encryption expert, he uses aerial drones to spy on his opponents in the Apex Arena without being seen. Orphans raised on the streets of Suotamo, Tae Joon and his foster sister Mila Alexander escaped a life of squalor by becoming computer engineers, designing drones used by the Syndicate to transmit the Apex Games throughout the Outlands. But two years ago, Tae Joon and Mila stumbled upon an algorithm that could predict the result of any Apex Games match, hidden away in the Games’ own computer systems. That caught the attention of the wrong people - the next day, Mila disappeared, and Tae Joon was forced into hiding after he was framed for her murder. With his reputation destroyed, and the Syndicate after him, he gave up his identity, his face, and his family in order to facilitate his redemption. Wanting to get closer to the people who framed him, Tae Joon planned to join the games but thought he wouldn't be able to pass the games' qualifiers. He then hacked into the games' mainframe and put himself in their records as a legend, but not before blowing up Kings Canyon's Repulsor Tower to serve as a distraction. This allowed the entry of hostile wildlife on Kings Canyon and disruption of the games. Now joining the games as the combatant known as Crypto, he seeks justice - and revenge.")
Legend.create!(name: "Wattson", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/wattson-tile.png", passive_name: "SPARK OF GENIUS", passive_image_url: "https://i.imgur.com/SWycCJ5.png", tactical_name: "PERIMETER SECURITY", tactical_image_url: "https://i.imgur.com/0KPxRnN.png", ultimate_name: "INTERCEPTION PYLON", ultimate_image_url: "https://i.imgur.com/WkAhTPF.png", lore: "Natalie Paquette is a familiar face in the Apex Games, though for a different reason than most. Daughter of the Games’ lead electrical engineer Luc Paquette, she studied his manuals to stay close to him and discovered her calling at a young age. Though she could be completely distracted one moment and hyper-focused the next, electricity grounded her – its ordered, predictable flow made sense in a way the rest of the world didn’t. She devoured every book she could on the subject, and eventually became such a skilled engineer that she was commissioned by the Syndicate to build the Apex Games’ Modified Containment Ring. Unfortunately, her father died the day it was revealed, leaving her alone. At her lowest moment, a group of competitors invited her to return to the arena with them, assuring her she would always have a home. She now fights alongside her friends in the arena she helped build, destroying incoming missiles, recharging shields, creating fences, and using her pylon to silence fights that get too loud. Nobody knows the arena better than Wattson – anyone who underestimates her is in for a shock.")
Legend.create!(name: "Octane", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/octane-tile.png", passive_name: "SWIFT MEND", passive_image_url: "https://i.imgur.com/36KmdbR.png", tactical_name: "STIM", tactical_image_url: "https://i.imgur.com/P270pEO.png", ultimate_name: "LAUNCH PAD", ultimate_image_url: "https://i.imgur.com/F1TlvBa.png", lore: "One day, Octavio Silva was bored. In fact, he was bored most days. Heir to the preoccupied CEOs of Silva Pharmaceuticals and wanting for nothing in life, he entertained himself by performing death-defying stunts and posting holovids of them for his fans to gawk over. So, this day, he decided to set the course record for a nearby Gauntlet by launching himself across the finish line – using a grenade. He later recounted that day as the single greatest day in his life. As he lay in triage hours later, the doctors informed him that the damage done to his legs meant his daredevil days were over. That didn’t sit well with Octavio, who turned to an old friend for help: Ajay Che, who he guilted into forging an order to replace his legs with bionic ones. Suddenly able to repair his limbs at a moment’s notice, Octavio decided petty online stunts weren’t enough: the ultimate adrenaline rush, the Apex Games, was calling. Now, he’s going to become an Apex Champion doing the most incredible, death-defying moves anyone’s ever seen. Maybe in the arena, he won’t be so bored.")
Legend.create!(name: "Mirage", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/mirage-tile.png", passive_name: "NOW YOU SEE ME...", passive_image_url: "https://i.imgur.com/cu2uxVs.png", tactical_name: "PSYCHE OUT", tactical_image_url: "https://i.imgur.com/lfJnYPQ.png", ultimate_name: "LIFE OF THE PARTY", ultimate_image_url: "https://i.imgur.com/4RoN4a5.png", lore: "Mirage is the kind of guy who likes to stand out. The youngest of four brothers, he perfected the art of fooling around to get attention. The one thing he took seriously was Holo-Pilot technology: introduced to the illusion-creating tech by his famed engineer mother Evelyn Witt, he pored over the mechanisms and learned all he could about them. Even when his brothers went missing during the Frontier War, Mirage and his mother continued to develop holo devices, and the work brought them closer. While working as a bartender on the Paradise Lounge in Solace City to make some extra money, Mirage heard amazing stories from his patrons about the Apex Games and the wealth and glory that came with victory. As good as both of those sounded, he knew he couldn't risk leaving his mother childless – until she gave him a set of customized holo devices and told him to follow his dream. Mirage is now the life of the Apex Games, outwitting opponents and charming audiences across the Outlands.")

Legend.create!(name: "Caustic", 
legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/caustic-tile.png", 
passive_name: "", 
passive_image_url: "", 
tactical_name: "", 
tactical_image_url: "", 
ultimate_name: "", 
ultimate_image_url: "", 
lore: "")

Legend.create!(name: "", 
legend_image_url: "", 
passive_name: "", 
passive_image_url: "", 
tactical_name: "", 
tactical_image_url: "", 
ultimate_name: "", 
ultimate_image_url: "", 
lore: "")

Legend.create!(name: "", 
legend_image_url: "", 
passive_name: "", 
passive_image_url: "", 
tactical_name: "", 
tactical_image_url: "", 
ultimate_name: "", 
ultimate_image_url: "", 
lore: "")


Legend.create!(name: "BloodHound", legend_image_url: "https://trackercdn.com/cdn/apex.tracker.gg/legends/bloodhound-tile.png", passive_name: "Tracker", passive_image_url: "https://i.imgur.com/JE5Bhfm.png", tactical_name: "Eye Of The Allfather", tactical_image_url: "https://i.imgur.com/CTlpe9W.png", ultimate_name: "Beast Of The Hunt", ultimate_image_url: "https://i.imgur.com/Hty4tvG.png", lore: "Bloodhound is known across the Outlands as one of the greatest game hunters the Frontier has ever seen. The child of two engineers stationed at the New Dawn industrial plant on Talos, Bloodhound was taken in by their uncle Artur after a meltdown destroyed the facility and killed both their parents. Artur taught them the Old Ways, a belief system that focuses on the glory of nature and rejects modern technology. Yet Bloodhound was constantly drawn to technological marvels, and ultimately used both new and old methods to take down a Goliath that preyed on the people of their village, forever changing their life’s path. Bloodhound's unparalleled tracking skills are a boon to any team they join, helping them root out hidden opponents and track enemy movements. Calling on Earth's Old Norse Gods to guide them, Bloodhound believes that destiny is a path that has already been laid out, eventually carrying all to their death. But with that knowledge comes strength, because until that day comes, Bloodhound knows they can't be stopped.")


t.string "name"
t.string "legend_image_url"
t.string "passive_name"
t.string "passive_image_url"
t.string "tactical_name"
t.string "tactical_image_url"
t.string "ultimate_name"
t.string "ultimate_image_url"
t.text "lore"